CREATE VIEW GORUNUMLER AS  
SELECT  
K.KULLANICI_ADI AS 'KULLANICI NUMARASI', 
K.AD AS ADI,
K.SOYAD AS SOYADI ,
K.AD + ' ' + K.SOYAD AS FULNAME,
K.MAÝL,
A.NAME AS 'ADRES BAÞLIÐI',
A.ACIKLAMA AS ADRES,
T.TC_NO AS 'TC KÝMLÝK NUMARASI ' ,
T.SERI_NO AS 'SERÝ KÝMLÝK NUMARASI',
T.DOGUMYERI AS 'DOÐUM YERÝ' ,
T.UYRUK AS UYRUK,
C.EV AS 'EV TELEFONU',
C.CEP AS 'CEP TELEFONU',
C.FAX AS 'FAX NUMARASI'  
FROM [dbo].[KULLANICI] AS K 
INNER JOIN ADRES AS A ON A.KULLANICI_ADI_ID = K.KULLANICI_ADI
INNER JOIN  KIMLIKBILGILERI AS T ON  A.KULLANICI_ADI_ID = T.ID 
INNER JOIN  TEL AS C ON  A.KULLANICI_ADI_ID = C.ID 