--CREATE TRIGGER TG1
--ON KULLANICI
--AFTER INSERT 
--AS
--BEGIN
--	SELECT'TEBRÝKLER , YENÝ ÜYE KAYDI GERÇEKLEÞTÝRÝLDÝ'
--END

--CREATE TRIGGER TG2 
--ON SIPARIS_DETAY
--AFTER INSERT 
--AS
--BEGIN
--	SELECT 'FATURANIZ OLUÞTURULDU'
--END


--CREATE TRIGGER TG3
--ON KIMLIKBILGILERI
--AFTER UPDATE 
--AS 
--IF UPDATE (TC_NO)
--	BEGIN
--	PRINT 'LÜTFEN DÝÐER KÝMLÝK BÝLGÝLERÝNÝZÝDE GÜNCELLEYÝNÝZ !'
--	END